comment: Get the list of deprecated playbooks.
commonfields:
  id: getDeprecatedPlaybooks
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.10.0
    itemVersion: 2.1.3
    packID: HealthCheck
    packName: System Diagnostics and Health Check
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
dockerimage: demisto/python3:3.11.10.111526
enabled: true
engineinfo: {}
mainengineinfo: {}
name: getDeprecatedPlaybooks
pswd: ""
runas: DBotWeakRole
runonce: false
script: |
  register_module_line('getDeprecatedPlaybooks', 'start', __line__())
  demisto.debug('pack name = System Diagnostics and Health Check, pack version = 2.1.3')



  payload = {'query': 'deprecated:T'}
  res = demisto.executeCommand("core-api-post", {"uri": "playbook/search", "body": json.dumps(payload)})[0]["Contents"]["response"]

  if not res['playbooks']:
      res['playbooks'] = []

  wList = []
  for item in res['playbooks']:
      wList.append({'Name': item['name']})

  md = tableToMarkdown('List of Deprecated Playbooks', wList)
  return_results({
      'Contents': wList,
      'ContentsFormat': formats['text'],
      'HumanReadable': md,
      'EntryContext': {'DeprecatedPlaybooks': [wList]}
  })

  register_module_line('getDeprecatedPlaybooks', 'end', __line__())
scripttarget: 0
subtype: python3
system: true
tags:
- statusreview
type: python
