comment: Get the count of custom, OOTB and deprecated playbooks.
commonfields:
  id: getPlaybooksCount
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.10.0
    itemVersion: 2.1.3
    packID: HealthCheck
    packName: System Diagnostics and Health Check
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
dockerimage: demisto/python3:3.10.14.95137
enabled: true
engineinfo: {}
mainengineinfo: {}
name: getPlaybooksCount
pswd: ""
runas: DBotWeakRole
runonce: false
script: |
  register_module_line('getPlaybooksCount', 'start', __line__())
  demisto.debug('pack name = System Diagnostics and Health Check, pack version = 2.1.3')



  payload1 = {'query': 'system:T'}
  res1 = demisto.executeCommand("core-api-post", {"uri": "playbook/search",
                                "body": json.dumps(payload1)})[0]["Contents"]["response"]

  if not res1['playbooks']:
      res1['playbooks'] = []


  payload2 = {'query': 'system:F'}
  res2 = demisto.executeCommand("core-api-post", {"uri": "playbook/search",
                                "body": json.dumps(payload2)})[0]["Contents"]["response"]

  if not res2['playbooks']:
      res2['playbooks'] = []

  payload3 = {'query': 'deprecated:T'}
  res3 = demisto.executeCommand("core-api-post", {"uri": "playbook/search",
                                "body": json.dumps(payload3)})[0]["Contents"]["response"]

  if not res3['playbooks']:
      res3['playbooks'] = []


  wList = []
  wList.append({"OOTB": len(res1["playbooks"]), "Custom": len(res2["playbooks"]), "Deprecated": len(res3["playbooks"])})

  return_results({"total": len(wList), "data": wList})

  register_module_line('getPlaybooksCount', 'end', __line__())
scripttarget: 0
subtype: python3
system: true
tags:
- statusreview
- widget
type: python
