comment: Get the count of big workplan, big tasks playbooks and the playbooks which
  automatically turned in to quiet mode.
commonfields:
  id: getPlaybooksHealthStatus
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.10.0
    itemVersion: 2.1.3
    packID: HealthCheck
    packName: System Diagnostics and Health Check
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
dockerimage: demisto/python3:3.10.14.95137
enabled: true
engineinfo: {}
mainengineinfo: {}
name: getPlaybooksHealthStatus
pswd: ""
runas: DBotWeakRole
runonce: false
script: |
  register_module_line('getPlaybooksHealthStatus', 'start', __line__())
  demisto.debug('pack name = System Diagnostics and Health Check, pack version = 2.1.3')



  res = demisto.executeCommand("core-api-get", {"uri": "diagnostics/checks"})[0]["Contents"]["response"]

  wList = []
  wList.append({"Big Workplans > 3 MB": res["checkRuns"]["diagnostic.workplan.big.workplans"]["result"]["metrics"]["total"],
                "Big tasks": res["checkRuns"]["diagnostic.workplan.big.tasks"]["result"]["metrics"],
                "Tasks turned to quiet mode": res["checkRuns"]["diagnostic.workplan.auto.quiet.task"]["result"]["metrics"]})

  return_results({"total": len(wList), "data": wList})

  register_module_line('getPlaybooksHealthStatus', 'end', __line__())
scripttarget: 0
subtype: python3
system: true
tags:
- statusreview
- widget
type: python
