commonfields:
  id: PlaybookAutoGeneratorDynamicSectionMessage
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.10.0
    itemVersion: 1.0.7
    packID: Use_Case_Builder
    packName: Use Case Builder
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
dockerimage: demisto/python3:3.10.14.100715
enabled: true
engineinfo: {}
mainengineinfo: {}
name: PlaybookAutoGeneratorDynamicSectionMessage
pswd: ""
runas: DBotWeakRole
runonce: false
script: |
  register_module_line('PlaybookAutoGeneratorDynamicSectionMessage', 'start', __line__())
  ### pack version: 1.0.7




  def main():
      incident = demisto.incident()
      incident_name = incident.get('name', '')
      usecasegeneratorkey = incident.get('CustomFields', {}).get('usecasebuilderautogeneratorkey', 0)

      if not incident_name:
          demisto.results(
              "This tool will help you develop, track, and maintain your use cases. As well as quickly generate custom "
              "playbooks to get you started on your automation journey! \n\nOnce you have created your use case, "
              "head over to the Downloads tab to retrieve your use case document")
      elif usecasegeneratorkey is not None:
          message = f'**{incident_name}** - has been generated and is now available in your playbook collection'

          dynamic_section = {
              "Type": 1,
              "ContentsFormat": "markdown",
              "Contents": message,
          }

          demisto.results(dynamic_section)


  if __name__ in ("__main__", "__builtin__", "builtins"):
      main()

  register_module_line('PlaybookAutoGeneratorDynamicSectionMessage', 'end', __line__())
scripttarget: 0
subtype: python3
system: true
tags:
- dynamic-section
type: python
