comment: Get the list of custom playbooks created in last 30 days.
commonfields:
  id: getCustomPlaybooks
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.10.0
    itemVersion: 2.1.3
    packID: HealthCheck
    packName: System Diagnostics and Health Check
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
dockerimage: demisto/python3:3.10.14.95137
enabled: true
engineinfo: {}
mainengineinfo: {}
name: getCustomPlaybooks
pswd: ""
runas: DBotWeakRole
runonce: false
script: |
  register_module_line('getCustomPlaybooks', 'start', __line__())
  demisto.debug('pack name = System Diagnostics and Health Check, pack version = 2.1.3')



  import dateutil.parser
  import pytz


  payload = {'query': 'system:F'}
  res = demisto.executeCommand("core-api-post", {"uri": "playbook/search", "body": json.dumps(payload)})[0]["Contents"]["response"]

  if not res['playbooks']:
      res['playbooks'] = []

  playbooksList = []
  for item in res["playbooks"]:
      playbook = {}
      if (item.get('system') is None):
          insertion_date = dateutil.parser.parse(item['modified'])
          diffretiation = pytz.utc.localize(datetime.utcnow()) - insertion_date
          if diffretiation.days < 30:
              playbook['name'] = item['name']
              playbooksList.append(playbook)

  return_results({"total": len(playbooksList), "data": playbooksList})

  register_module_line('getCustomPlaybooks', 'end', __line__())
scripttarget: 0
subtype: python3
system: true
tags:
- statusreview
- widget
type: python
