contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 5.5.0
    itemVersion: 3.0.2
    packID: qualys
    packName: Qualys
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Launches a compliance policy report and then fetches the report when
  it's ready.
id: Launch And Fetch Compliance Policy Report - Qualys
inputs:
- description: The template ID of the report you want to launch. Can be found by running
    the command qualys-report-template-list.
  key: template_id
  playbookInputQuery: null
  required: true
  value: {}
- description: One output format can be specified. When output_format=pdf is specified,
    the Secure PDF Distribution can be used.
  key: output_format
  playbookInputQuery: null
  required: true
  value: {}
- description: A user-defined report title. The title may have a maximum of 128 characters.
    For a PCI compliance report, the report title is provided by Qualys and cannot
    be changed.
  key: report_title
  playbookInputQuery: null
  required: false
  value: {}
- description: (Valid for CSV format report only). Specify hide_header=1 to omit the
    header information from the report. By default, this information is included.
  key: hide_header
  playbookInputQuery: null
  required: false
  value: {}
- description: Specify users who will receive the email notification when the report
    is complete (i.e., supply a distribution group ID). Where do I find this ID? Log
    in to your Qualys account, go to Users > Distribution Groups and select Info for
    a group in the list.
  key: recipient_group_id
  playbookInputQuery: null
  required: false
  value: {}
- description: (Required for secure PDF distribution, Manager or Unit Manager only)
    Used for secure PDF report distribution when this feature is enabled in the user's
    account (under Reports > Setup > Report Share). The password to be used for encryption.
    - the password must have a minimum of 8 characters (ascii), and a maximum of 32
    characters - the password must contain alpha and numeric characters - the password
    cannot match the password for the user’s Qualys account. - the password must follow
    the password security guidelines defined for your subscription (under Users >
    Setup > Security)
  key: pdf_password
  playbookInputQuery: null
  required: false
  value: {}
- description: Used for secure PDF distribution. The report recipients in the form
    of one or more distribution group names, as defined using the Qualys UI. Multiple
    distribution groups are comma separated. A maximum of 50 distribution groups may
    be entered.
  key: recipient_group
  playbookInputQuery: null
  required: false
  value: {}
- description: (Optional for compliance report) For a compliance report (except a
    PCI report), specify the IPs/ranges you want to include in the report. Multiple
    IPs and/or ranges are comma separated.
  key: ips
  playbookInputQuery: null
  required: false
  value: {}
- description: (Optional for compliance report) For a compliance report (except a
    PCI report), specify asset groups IDs which identify hosts to include in the report.
    Multiple asset group IDs are comma separated. Looking for asset group IDs? Use
    the asset_group_list.php function (in the API v1 User Guide).
  key: asset_group_ids
  playbookInputQuery: null
  required: false
  value: {}
- description: Specifies the policy to run the report on. A valid policy ID must be
    entered.
  key: policy_id
  playbookInputQuery: null
  required: true
  value: {}
- description: In the policy report output, show only results for a single host instance.
    Specify the ID for the host to include in the report. A valid host ID must be
    entered.
  key: host_id
  playbookInputQuery: null
  required: false
  value: {}
- description: Specifies a single instance on the selected host. The instance string
    may be “os” or a string like “oracle10:1:1521:ora10204u”.
  key: instance_string
  playbookInputQuery: null
  required: false
  value: {}
name: Launch And Fetch Compliance Policy Report - Qualys
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: feaf59d2-f107-4395-862c-895cd5406872
      iscommand: false
      name: ""
      version: -1
    taskid: feaf59d2-f107-4395-862c-895cd5406872
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      asset_group_ids:
        simple: ${inputs.asset_group_ids}
      hide_header:
        simple: ${inputs.hide_header}
      host_id:
        simple: ${inputs.host_id}
      instance_string:
        simple: ${inputs.instance_string}
      ips:
        simple: ${inputs.ips}
      output_format:
        simple: ${inputs.output_format}
      pdf_password:
        simple: ${inputs.pdf_password}
      policy_id:
        simple: ${inputs.policy_id}
      recipient_group:
        simple: ${inputs.recipient_group}
      recipient_group_id:
        simple: ${inputs.recipient_group_id}
      report_title:
        simple: ${inputs.report_title}
      template_id:
        simple: ${inputs.template_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: QualysV2
      description: Run compliance policy report
      id: 5b82fc23-5579-48f5-8c52-81f17f565803
      iscommand: true
      name: qualys-report-launch-compliance-policy
      script: QualysV2|||qualys-report-launch-compliance-policy
      type: regular
      version: -1
    taskid: 5b82fc23-5579-48f5-8c52-81f17f565803
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 210
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      execution-timeout:
        simple: "180"
      file_format:
        simple: ${inputs.output_format}
      id:
        simple: ${Qualys.Report.ID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: QualysV2
      description: Download report
      id: 973d836a-4892-436b-8d2a-059160cc7f6c
      iscommand: true
      name: qualys-report-fetch
      script: QualysV2|||qualys-report-fetch
      type: regular
      version: -1
    taskid: 973d836a-4892-436b-8d2a-059160cc7f6c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 540
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 0
      wait: 1
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      Ids:
        simple: ${Qualys.Report.ID}
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: id
      PollingCommandName:
        simple: qualys-report-list
      Timeout:
        simple: "30"
      dt:
        simple: Qualys.Report(val.STATUS.STATE != 'Finished').ID.
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      id: 9fe76d77-ac51-4c04-862b-eb39c73eecb0
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 9fe76d77-ac51-4c04-862b-eb39c73eecb0
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 585,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
