contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.2.2
    packID: CortexXpanse
    packName: Cortex Xpanse
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Additional enrichment via cloud service providers and other applicable
  IT and security tools.
id: Xpanse - Alert Enrichment
inputs:
- description: ""
  key: Provider
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: xpanseprovider
      root: incident
- description: ""
  key: IP
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: xpanseip
      root: incident
name: Xpanse - Alert Enrichment
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7985bd85-1331-4763-809c-e7290f2e757c
      iscommand: false
      name: ""
      version: -1
    taskid: 7985bd85-1331-4763-809c-e7290f2e757c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Provider
          operator: isEqualString
          right:
            value:
              simple: Amazon Web Services
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.IP
          operator: isNotEmpty
      label: AWS
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Provider
          operator: isEqualString
          right:
            value:
              simple: Google
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.IP
          operator: isNotEmpty
      label: GCP
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Provider
          operator: isEqualString
          right:
            value:
              simple: Azure
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.IP
          operator: isNotEmpty
      label: Azure
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      AWS:
      - "5"
      Azure:
      - "6"
      GCP:
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f00a4dad-8b94-4120-8b38-66b279d5b2c0
      iscommand: false
      name: What is the provider?
      type: condition
      version: -1
    taskid: f00a4dad-8b94-4120-8b38-66b279d5b2c0
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a3720e48-9eaa-44f2-8387-0b41c9987c78
      iscommand: false
      name: Additional Enrichment
      type: title
      version: -1
    taskid: a3720e48-9eaa-44f2-8387-0b41c9987c78
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 930
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c108a033-333d-408a-8c8f-7fec7c072f70
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: c108a033-333d-408a-8c8f-7fec7c072f70
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1230
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      GcpIP:
        complex:
          root: inputs.IP
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Given the IP address, this playbook enriches GCP and Firewall information.
      id: bb9c5569-7c11-44d6-82bc-2cdc01fdb8c1
      iscommand: false
      name: GCP - Enrichment
      playbookId: GCP - Enrichment
      type: playbook
      version: -1
    taskid: bb9c5569-7c11-44d6-82bc-2cdc01fdb8c1
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1160,
          "y": 450
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      AwsIP:
        complex:
          root: inputs.IP
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Given the IP address, this playbook enriches EC2 and IAM information.
      id: f4efa98a-0b7f-4ef3-8fdc-95e71d706276
      iscommand: false
      name: AWS - Enrichment
      playbookId: AWS - Enrichment
      type: playbook
      version: -1
    taskid: f4efa98a-0b7f-4ef3-8fdc-95e71d706276
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1570,
          "y": 400
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      AzureIP:
        complex:
          root: inputs.IP
    separatecontext: true
    skipunavailable: true
    task:
      brand: ""
      description: Given an IP address, this playbook enriches Azure Compute, Microsoft
        Graph User, and IAM information and outputs Azure Compute, Microsoft Graph
        User, and IAM information.
      id: 626873bd-fe9f-4fba-87fc-64553e320d32
      iscommand: false
      name: Azure - Enrichment
      playbookId: Azure - Enrichment
      type: playbook
      version: -1
    taskid: 626873bd-fe9f-4fba-87fc-64553e320d32
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 750,
          "y": 520
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1245,
        "width": 1500,
        "x": 450,
        "y": 50
      }
    }
  }
