contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: 6.8.0
    itemVersion: 1.2.2
    packID: CortexXpanse
    packName: Cortex Xpanse
    packPropagationLabels:
    - all
    prevname: ""
    propagationLabels: []
    toServerVersion: ""
description: Default alert handling for Cortex Xpanse alerts.
id: Xpanse - Alert Handler
inputs:
- description: Whether to write data back to Cortex Xpanse.
  key: WriteToXpanse
  playbookInputQuery: null
  required: false
  value:
    simple: "False"
name: Xpanse - Alert Handler
outputs: []
starttaskid: "0"
system: true
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 51e81457-177e-4950-8197-6bfcaabd0be7
      iscommand: false
      name: ""
      version: -1
    taskid: 51e81457-177e-4950-8197-6bfcaabd0be7
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -80
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    scriptarguments:
      RemoteIP:
        complex:
          accessor: xpanseip
          root: incident
      RemotePort:
        complex:
          accessor: xpanseport
          root: incident
      ScanNumber:
        simple: "1"
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Looks at what ASM sub-type the alert is and uses NMap to do a validation
        scan.
      id: 2dbfd762-668c-4085-89db-75eeae61e6fe
      iscommand: false
      name: Xpanse - NMap - Detect Service
      playbookId: Xpanse - NMap - Detect Service
      type: playbook
      version: -1
    taskid: 2dbfd762-668c-4085-89db-75eeae61e6fe
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 180
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 30d2124a-8ddf-4901-8bd7-089476652a10
      iscommand: false
      name: Complete
      type: title
      version: -1
    taskid: 30d2124a-8ddf-4901-8bd7-089476652a10
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      iscommand: false
      max: 100
      wait: 1
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      description: Enrichment on the alert itself using Cortex Xpanse APIs.
      id: c47edf3e-f390-4c0c-8e46-666c4429f94d
      iscommand: false
      name: Xpanse - Alert Self-Enrichment
      playbookId: Xpanse - Alert Self-Enrichment
      type: playbook
      version: -1
    taskid: c47edf3e-f390-4c0c-8e46-666c4429f94d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 470
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "10"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: e55bd85b-30af-42a7-8556-2d5bf31ddfa5
      iscommand: false
      name: Xpanse - Alert Enrichment
      playbookId: Xpanse - Alert Enrichment
      type: playbook
      version: -1
    taskid: e55bd85b-30af-42a7-8556-2d5bf31ddfa5
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 630
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e7947bb6-bd91-43f4-8b58-9ea6e402aa4d
      iscommand: false
      name: Is the service still exposed?
      type: title
      version: -1
    taskid: e7947bb6-bd91-43f4-8b58-9ea6e402aa4d
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8db016d6-0000-4d73-8b2e-d6d5d1ab0e2f
      iscommand: false
      name: Asset and Alert Enrichment
      type: title
      version: -1
    taskid: 8db016d6-0000-4d73-8b2e-d6d5d1ab0e2f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 340
        }
      }
  "7":
    continueonerrortype: ""
    form:
      description: Add one or more tags to the assets(s) associated with the current
        Cortex XSOAR incident.
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: What tag(s) do you want to add to asset(s)?
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: true
        tooltip: Specify a comma-separated list of tags you want to add to the asset(s)
          associated to the current Cortex XSOAR incident.
        type: shortText
      sender: Your SOC team
      title: Determine tags to add to asset
      totalanswers: 0
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 0
        retriesinterval: 0
      to: null
    nexttasks:
      '#none#':
      - "9"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Add one or more tags to the assets(s) associated with the current
        Cortex XSOAR incident.
      id: 54995d00-c6c0-4549-8ded-319d5bc01e0e
      iscommand: false
      name: Determine tags to add to asset(s)
      type: collection
      version: -1
    taskid: 54995d00-c6c0-4549-8ded-319d5bc01e0e
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1020
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      asm_id_list:
        complex:
          accessor: xpanseassetids
          root: incident
          transformers:
          - args:
              chars:
                value:
                  simple: '[]'
            operator: StripChars
          - args:
              limit: {}
              replaceWith: {}
              toReplace:
                value:
                  simple: '"'
            operator: replace
      tags:
        complex:
          accessor: Answers
          root: Determine tags to add to asset
          transformers:
          - operator: LastArrayElement
          - args:
              field:
                value:
                  simple: "0"
            operator: getField
          - args:
              delimiter:
                value:
                  simple: ','
            operator: split
    separatecontext: false
    skipunavailable: false
    task:
      brand: Cortex Xpanse
      description: Assigns tags to a list of assets.
      id: 3279b4b2-f6ca-4f10-8bcf-c199409bcf5f
      iscommand: true
      name: Assign Tag to Asset(s)
      script: Cortex Xpanse|||asm-tag-asset-assign
      type: regular
      version: -1
    taskid: 3279b4b2-f6ca-4f10-8bcf-c199409bcf5f
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1180
        }
      }
  "10":
    conditions:
    - condition:
      - - ignorecase: true
          left:
            iscontext: true
            value:
              simple: inputs.WriteToXpanse
          operator: isEqualString
          right:
            value:
              simple: "True"
      label: "yes"
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Determine whether the playbook should write data back to Cortex
        Xpanse.
      id: 62fb488b-6b5a-469d-800e-80a6e253d8b1
      iscommand: false
      name: Are we writing to Cortex Xpanse?
      type: condition
      version: -1
    taskid: 62fb488b-6b5a-469d-800e-80a6e253d8b1
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 790
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "10_7_yes": 0.49
    },
    "paper": {
      "dimensions": {
        "height": 1515,
        "width": 380,
        "x": 450,
        "y": -80
      }
    }
  }
